id: P010760
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:23:16.312862
source_metadata:
  id: bdr:W30023
  title: རྩིས་རིག
  author: ''
  volumes:
    1b38c331381c4b66bd6aa6359d91a022:
      image_group_id: I5743
      title: ''
      volume_number: 1
      total_pages: 883
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
