id: IFDBF938F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T16:32:00+00:00'
last_modified: '2022-06-08T17:19:41.373446+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30023
  title: རྩིས་རིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    388D:
      image_group_id: I5743
      title: ''
      total_pages: 883
      order: 1
      base_file: 388D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
